### ISSUE TITLE
[V5] - Consider Napa.js

### ISSUE THREAD

**Issue by ParadoxOrigins** [ParadoxalCorp/felix-production#2]
https://github.com/Microsoft/napajs 

Well, if SharedArrayBuffer isn't implemented in node.js before that

**Comment by LevitatingBusinessMan** [comment]
Napa.js is pretty cool but why would you need. How are you going to make use of it 🤔

**Comment by LevitatingBusinessMan** [comment]
haha nvm me I thought workers had to be assigned individual functions but they solve their own shit.

**Comment by ParadoxOrigins** [comment]
Anyway there's not any drafts for v5 yet. There are drafts for various changes in v4 structure already though and i think i won't start working on v5 anytime soon unless Felix somehow start growing at a rate of 5k guilds/day
