### ISSUE TITLE
Find an efficient way to make leaderboard

### ISSUE THREAD

**Issue by ParadoxOrigins** [ParadoxalCorp/felix-production#63]
RethinkDB is in fact trash and as hotfix atm we're caching the whole users database 3 times, this is no way near being efficient 
- [x] Done

**Comment by CFTheMaster** [comment]
oof

**Comment by InternalCosmos** [comment]
oof

**Comment by CFTheMaster** [comment]
why not use Redis for cache and let that take most of the heavy hitting and just store small parts in RethinkDB :thinking:

**Comment by ParadoxOrigins** [comment]
I expected RethinkDB to not be *that* bad, basically hoped i wouldn't have to cache everything but apparently life isn't that simple (╯°□°）╯︵ ┻━┻

**Comment by CFTheMaster** [comment]
```js
let redis = require('redis');
let client = redis.createClient(process.env.REDIS_PORT, process.env.REDIS_HOST);
if (typeof process.env.REDIS_PASSWORD)
	client.auth(process.env.REDIS_PASSWORD);
var handler = function() {};

client.get('some-key-value', function (err, result) {
	if (err || !result)
	   execute_function(something, handler);
	else
		res.end(result);
});
let handler = function(response)
{
	response = JSON.stringify(response);
	client.setex('some-key-value', 21600, response);
	res.end(response);
};```
I mean it's quite easy to do

**Comment by ParadoxOrigins** [comment]
nah it just absolutely doesn't work like that

**Comment by CFTheMaster** [comment]
oof

**Comment by CFTheMaster** [comment]
I have never done JS

**Comment by CFTheMaster** [comment]
well only for websites

**Comment by CFTheMaster** [comment]
[I have no idea but this might help?????](https://community.risingstack.com/redis-node-js-introduction-to-caching/)

**Comment by ParadoxOrigins** [comment]
The current issue is that if i don't cache everything, i need to have RethinkDB do the sorting and all to build a leaderboard, however RethinkDB takes 5 seconds to do that and uses 100% of the CPU while doing that. If i cache everything, it takes basically too much RAM, and that's not cool.

**Comment by CFTheMaster** [comment]
so what you are saying is that you want to (maybe) cache small parts that get used the most?

**Comment by CFTheMaster** [comment]
in an efficient and effective manner

**Comment by ParadoxOrigins** [comment]
Well a solution would be to only cache the needed data yeah but implementing that in the current structure is going to take time

**Comment by CFTheMaster** [comment]
why not give users so called keys in the database
and instead of going through the whole database search that particular users key
and cache all those keys to something like Redis

**Comment by Niputi** [comment]
... and the chat continued on discord

**Comment by ParadoxOrigins** [comment]
Fixed by back-logging the necessary data to Redis's sorted sets, from the tests done it seems to perform at least 500% better

**Comment by ParadoxOrigins** [comment]
forgot to close that
